export type RootStackParamList = {
  Splash: undefined;
  Login: undefined;
  Home: undefined;
  Participants: undefined;
  Reports: undefined;
  Profile: undefined;
  PreVR: { patientId: number,age:number,studyId:number };
   PostVR: { patientId: number,age:number,studyId:number,RandomizationId?: string | number};
  PreVRAssessment: { patientId: number,age:number,studyId:number,RandomizationId?: string | number };
  PostVRAssessment: { patientId: number,age:number,studyId:number,RandomizationId?: string | number};
  PreAndPostVR: { patientId: number,age:number,studyId:number };
  DistressThermometerScreen: { patientId: number,age:number,studyId:number,isBaseline?:boolean };
  EdmontonFactGScreen: { patientId: number,age:number,studyId:number };
  AdverseEventForm: { patientId: number,age:number,studyId:number,RandomizationId?: string | number };
  StudyObservation: { patientId: number,age:number,studyId:number };
  PatientDashboard: { patientId: number,age:number,studyId:number };
  ExitInterview: { patientId: number,age:number,studyId:number };
  DoctorDashboard: undefined;
  PhysicianDashboard: undefined;
  VRSessionPage: { patientId: number, age: number, studyId: number, sessionNo?: string, sessionType?: string , RandomizationId?: string | number, Gender?:string,phoneNumber?:string; SessionStatus?:string;
};
  SessionSetupScreen: {patientId?:number,age?:number,studyId?:number,RandomizationId?: string | number,Gender?:string,phoneNumber?:string,sessionNo?:string};
  ParticipantInfo: { patientId: number,age:number,studyId:number };
  SessionControlScreen: {patientId?: number,studyId?:number; age?:number,therapy?:string; backgroundMusic?:string;language?:string;session?:string,SessionNo?:string };
  SessionCompletedScreen: {patientId?:number,SessionNo:string;};
  SocioDemographic: { patientId?: number,age?:number,studyId?:number };
  PatientScreening: { patientId: number,age:number,studyId:number };
  Screening: { patientId: number,age:number };
  FactG: { patientId: number,age:number };
  DistressThermometerList:{ patientId: number,age:number,studyId:number };
  StudyObservation_List:{patientId:number,age:number,studyId:number};
  FactGAssessmentHistory: {patientId:number,age:number,studyId:number};
  VRPrePostList: {patientId:number,age:number,studyId:number};
  AdverseEventReportsHistory: {patientId:number,age:number,studyId:number};
  StudyGroupAssignment: { patientId: number,age:number,studyId:number };
  InformedConsent: { patientId: number,age:number,studyId:number };
  VRSessionsList: { patientId: number,age:number,studyId:number,RandomizationId?:string,Gender?:string,phoneNumber?:string };
  SessionDetailsScreen: { patientId: number,age:number,studyId:number,sessionDetails:any };
  AboutUs:undefined;
};
 